version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lernexa-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lernexa
    ports:
      - '3306:3306'
    volumes:
      - lernexa-db-data:/var/lib/mysql

volumes:
  lernexa-db-data:
